### ISSUE TITLE
No method Phone Verification check verification status

### ISSUE THREAD

**Issue by tcjcodes** [twilio/authy-java#60]
`PhoneVerification` doesn't have a convenience method for the `GET https://api.authy.com/protected/json/phones/verification/status` call

Docs: https://www.twilio.com/docs/verify/api/verification?code-sample=code-check-verification-status-using-phone-number-4&code-language=curl&code-sdk-version=default

**Comment by robinske** [comment]
This library is no longer actively maintained. The Authy API has been replaced with the [Twilio Verify API](https://www.twilio.com/docs/verify). Twilio will support the Authy API through November 1, 2022 for SMS/Voice. After this date, we’ll start to deprecate the service for SMS/Voice. Any requests sent to the API after May 1, 2023, will automatically receive an error.  Push and TOTP will continue to be supported through July 2023.

[Learn more about migrating from Authy to Verify.](https://www.twilio.com/blog/migrate-authy-to-verify)

Please visit the Twilio Docs for:
* [Verify + Java (Servlets) quickstart](https://www.twilio.com/docs/verify/quickstarts/java-servlets)
* [Twilio Java helper library](https://www.twilio.com/docs/libraries/java)
* [Verify API reference](https://www.twilio.com/docs/verify/api)

Please direct any questions to [Twilio Support](https://support.twilio.com/hc/en-us). Thank you!
